// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwiekxkhsdkrcdwwqsry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aWVreGtoc2RrcmNkd3dxc3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDk2NzksImV4cCI6MjA1OTk4NTY3OX0.makF_VeykycN0YXBWFPRpZk1EO9wJS6rRWcJIbtJ6_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);